import type { NavItem } from '@/types';
import { ClipboardList, Database, FileCheck } from 'lucide-react';

/**
 * Generated main navigation items for catalogs (and similar modules).
 *
 * DO NOT edit this file manually. It is intended to be maintained by the
 * make:catalog generator in an idempotent way.
 *
 * Each item should be shown only if the user has the corresponding permission.
 * To keep core components free of permission wiring, we accept `can` here
 * and filter items accordingly.
 */
export function generatedMainNavItems(can: Record<string, boolean>): NavItem[] {
    const iconByUrl: Record<string, NavItem['icon']> = {
        '/catalogs/procedure-type': ClipboardList,
        '/catalogs/requirement': FileCheck,
    };

    // Keep this typed conversion so the core NavItem doesn't carry `perm`.
    const itemsWithPerm: Array<{ title: string; url: string; perm: string; icon?: NavItem['icon'] }> = [
        // Marker: BEGIN AUTO-GENERATED NAV ITEMS (make:catalog)
        { title: 'Tipos de trámite', url: '/catalogs/procedure-type', perm: 'catalogs.procedure-type.view' },
        { title: 'Requisitos', url: '/catalogs/requirement', perm: 'catalogs.requirement.view' },
        // Marker: END AUTO-GENERATED NAV ITEMS (make:catalog)
    ];

    return itemsWithPerm
        .filter((it) => can[it.perm] !== false)
        .map(({ perm: _perm, ...rest }) => ({ ...rest, icon: iconByUrl[rest.url] ?? rest.icon ?? Database }) satisfies NavItem);
}
