<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Catalog Routes
|--------------------------------------------------------------------------
|
| This file is reserved for catalog-like resources generated by the
| make:catalog command. The generator will append new route groups here in
| an idempotent way. Keeping all catalogs in a single file simplifies
| maintenance and route discovery.
|
*/

// Marker: BEGIN AUTO-GENERATED CATALOG ROUTES (make:catalog)
// Marker: END AUTO-GENERATED CATALOG ROUTES (make:catalog)
