<?php

declare(strict_types=1);

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\Factory;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsToMany;
use OwenIt\Auditing\Auditable as AuditableTrait;
use OwenIt\Auditing\Contracts\Auditable as AuditableContract;

/**
 * ProcedureType model generated by make:catalog
 */
class ProcedureType extends Model implements AuditableContract
{
    /**
     * @use HasFactory<Factory>
     */
    use AuditableTrait, HasFactory;

    protected $table = 'procedure_types';

    /**
     * @var list<string>
     */
    protected $fillable = [
        'code',
        'name',
        'description',
        'workflow_requires_review_assignment',
        'workflow_requires_inspector_assignment',
        'workflow_requires_inspection',
        'workflow_requires_technical_response',
        'workflow_requires_decision',
        'reception_requires_all_recaudos',
        'reception_requires_file_uploads',
        'inspection_requires_photos',
        'inspection_requires_report',
        'decision_requires_document',
        'inspection_mode',
        'has_validity',
        'validity_years',
        'validity_months',
        'is_active',
        'sort_order',
    ];

    /**
     * @return array<string, string>
     */
    protected function casts(): array
    {
        return [
            'workflow_requires_review_assignment' => 'boolean',
            'workflow_requires_inspector_assignment' => 'boolean',
            'workflow_requires_inspection' => 'boolean',
            'workflow_requires_technical_response' => 'boolean',
            'workflow_requires_decision' => 'boolean',
            'reception_requires_all_recaudos' => 'boolean',
            'reception_requires_file_uploads' => 'boolean',
            'inspection_requires_photos' => 'boolean',
            'inspection_requires_report' => 'boolean',
            'decision_requires_document' => 'boolean',
            'has_validity' => 'boolean',
            'validity_years' => 'integer',
            'validity_months' => 'integer',
            'is_active' => 'boolean',
            'sort_order' => 'integer',
        ];
    }

    /**
     * @return BelongsToMany<Requirement, $this>
     */
    public function requirements(): BelongsToMany
    {
        return $this->belongsToMany(Requirement::class, 'procedure_type_requirements')
            ->withPivot(['sort_order', 'is_required', 'is_active'])
            ->withTimestamps()
            ->orderBy('procedure_type_requirements.sort_order');
    }
}
