<?php

declare(strict_types=1);

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\Factory;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsToMany;
use OwenIt\Auditing\Auditable as AuditableTrait;
use OwenIt\Auditing\Contracts\Auditable as AuditableContract;

/**
 * Requirement model generated by make:catalog
 */
class Requirement extends Model implements AuditableContract
{
    /**
     * @use HasFactory<Factory>
     */
    use AuditableTrait, HasFactory;

    protected $table = 'requirements';

    /**
     * @var list<string>
     */
    protected $fillable = [
        'code',
        'name',
        'description',
        'is_active',
        'sort_order',
    ];

    /**
     * @return array<string, string>
     */
    protected function casts(): array
    {
        return [
            'is_active' => 'boolean',
            'sort_order' => 'integer',
        ];
    }

    /**
     * @return BelongsToMany<ProcedureType, $this>
     */
    public function procedureTypes(): BelongsToMany
    {
        return $this->belongsToMany(ProcedureType::class, 'procedure_type_requirements')
            ->withPivot(['sort_order', 'is_required', 'is_active'])
            ->withTimestamps();
    }
}
